#!/bin/bash
xfsettingsd &
xfce4-volumed &
xfce4-power-manager &

nm-applet &

feh --bg-scale ~/.dotfiles/world-map-wallpaper.png &
unclutter -idle 1 -jitter 10 -root &
xsetroot -cursor_name 'left_ptr' &

dropboxd &

xmonad
