#!/bin/bash -l

[ -f /usr/lib/systemd/system/bumblebeed.service ] && sudo systemctl restart bumblebeed.service
/usr/lib/gnome-settings-daemon/gnome-settings-daemon &
/usr/lib/notification-daemon-1.0/notification-daemon &
gnome-screensaver &

nm-applet &

unclutter -idle 1 -jitter 10 -root &
xsetroot -cursor_name 'left_ptr' &

dropboxd &

export JAVA_FONTS=/usr/share/fonts/TTF
export _JAVA_OPTIONS='-Dswing.aatext=true -Dawt.useSystemAAFontSettings=on -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel' 

sleep 1 && ${1:-xmonad}
