#!/bin/bash

git ls-files "$@" |\
  parallel -j10 file | grep 'text$' | awk -F':' '{print $1}' |\
  parallel -j10 git blame --line-porcelain -- |\
  sed -n 's/^author //p' |\
  sort | uniq -c | sort -nr

