#!/usr/bin/env bash
WINDOW_ID=$(tmux display-message -t "$TMUX_PANE" -p '#{window_id}' 2>/dev/null)
TITLE=$(tmux display-message -t "$TMUX_PANE" -p '#W' 2>/dev/null)
TITLE="${TITLE#? }"
PREFIX="${1:+$1 }"
tmux rename-window -t "$WINDOW_ID" -- "${PREFIX}${TITLE}"
